### ISSUE TITLE
Dynamically Loading/Changing video hashedid

### ISSUE THREAD

**Issue by mpbunch** [mrdavidjcole/wistia-player-react#1]
When implementing:
<WistiaEmbed hashedId="someId" />

I changed "someId":
<WistiaEmbed hashedId={this.state.hashedId} />

and the new video(hashedid) will not/does not load.

**Comment by mpbunch** [comment]
I was able to get this working using the depreciated api and a settimeout()

(It works, but will need to check to see if the current this.state.media is already embeded, if yes, change video.time to new start position. else embed new video and set start time.)

```
setTimeout(function(){
      window.Wistia.embed(this.state.hashedid);
      window._wq.push({id:this.state.hashedid, onReady:function(video){
        video.bind('play', function() {
          video.time(this.state.video.starttime);
          return video.unbind;
        });
        video.play();
      }})
    },100)
```

**Comment by Raj6198** [comment]
same problem. any solution on this
